// export {default as Home} from './balcony3.png';
 export {default as Home} from './jcpioneerWeb2.png';
 export {default as Clients} from './jcpioneerWeb2.png';
 export {default as Res} from './jdcres2018b.pdf';
 export {default as Contact} from './jcpioneerWeb2b.png';
 export {default as image1} from './image1.png';
 export {default as image2} from './image2.png';
 export {default as image3} from './image3.png';
 export {default as image4} from './image4.png';
 export {default as image5} from './image5.png';
 export {default as image6} from './image6.png';