// export {default as Home} from './balcony3.png';
 export {default as Home} from './jcpioneerWeb2.png';
 export {default as Clients} from './jcpioneerWeb2.png';
 export {default as Res} from './jdcres2018b.pdf';
 export {default as Contact} from './jcpioneerWeb2b.png';
 export {default as image1} from './reelThumb.png';
 export {default as image2} from './sumoThumb.png';
 export {default as image3} from './wimThumb.png';
 export {default as image4} from './justinThumb.png';
 export {default as image5} from './karinaThumb.png';
 export {default as image6} from './greybackThumb.png';
 export {default as ytButton} from './ytPlay.png';